<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251231000001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Repair migration: Drop tables and recreate with correct Postgres IDENTITY columns';
    }

    public function up(Schema $schema): void
    {
        // Safe reset: we drop existing tables in correct dependency order
        $this->addSql('DROP TABLE IF EXISTS claim_item CASCADE');
        $this->addSql('DROP TABLE IF EXISTS claim CASCADE');
        $this->addSql('DROP TABLE IF EXISTS project CASCADE');
        $this->addSql('DROP TABLE IF EXISTS carbon_impact CASCADE');
        $this->addSql('DROP TABLE IF EXISTS material CASCADE');
        $this->addSql('DROP TABLE IF EXISTS "user" CASCADE');
        $this->addSql('DROP TABLE IF EXISTS messenger_messages CASCADE');

        // Recreate tables with GENERATED BY DEFAULT AS IDENTITY (Postgres equivalent of Auto Increment)
        $this->addSql('CREATE TABLE carbon_impact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(255) NOT NULL, amount DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE claim (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, claim_number VARCHAR(100) NOT NULL, policy_holder VARCHAR(255) NOT NULL, total_carbon_score DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE claim_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, material_id INT NOT NULL, claim_id INT NOT NULL, quantity_used DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5114B23AE308AC6F ON claim_item (material_id)');
        $this->addSql('CREATE INDEX IDX_5114B23A7096A49F ON claim_item (claim_id)');
        $this->addSql('CREATE TABLE material (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, carbon_footprint_per_unit DOUBLE PRECISION NOT NULL, category VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEA76ED395 ON project (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, google_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');

        $this->addSql('ALTER TABLE claim_item ADD CONSTRAINT FK_5114B23AE308AC6F FOREIGN KEY (material_id) REFERENCES material (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE claim_item ADD CONSTRAINT FK_5114B23A7096A49F FOREIGN KEY (claim_id) REFERENCES claim (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE carbon_impact CASCADE');
        $this->addSql('DROP TABLE claim CASCADE');
        $this->addSql('DROP TABLE claim_item CASCADE');
        $this->addSql('DROP TABLE material CASCADE');
        $this->addSql('DROP TABLE project CASCADE');
        $this->addSql('DROP TABLE "user" CASCADE');
        $this->addSql('DROP TABLE messenger_messages CASCADE');
    }
}
