<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251231000003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add missing material columns and seed comprehensive dataset';
    }

    public function up(Schema $schema): void
    {
        // 1. Add missing columns
        $this->addSql('ALTER TABLE material ADD unit VARCHAR(50) NOT NULL DEFAULT \'kg\'');
        $this->addSql('ALTER TABLE material ADD density DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE material ADD source_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE material ADD industry_average_factor DOUBLE PRECISION DEFAULT NULL');

        // 2. Seed Data
        // Clear existing to avoid duplicates if re-running
        $this->addSql('DELETE FROM material');

        // Reset sequence if possible (Postgres specific)
        // $this->addSql('ALTER SEQUENCE material_id_seq RESTART WITH 1');

        $materials = [
            // Concrete
            ["Concrete (C20/25)", 0.103, "Concrete", "kg", 2400],
            ["Concrete (C30/37)", 0.136, "Concrete", "kg", 2400],
            ["Concrete (Reinforced)", 0.180, "Concrete", "kg", 2500],
            ["Cement (Portland)", 0.850, "Concrete", "kg", 1400],

            // Timber/Wood
            ["Timber (Softwood)", 0.110, "Wood", "kg", 500],
            ["Timber (Hardwood)", 0.150, "Wood", "kg", 700],
            ["Plywood", 0.350, "Wood", "kg", 600],
            ["MDF (Medium Density Fibreboard)", 0.380, "Wood", "kg", 750],
            ["Cross Laminated Timber (CLT)", 0.110, "Wood", "kg", 500],

            // Metals
            ["Steel (Rebar)", 1.990, "Metal", "kg", 7850],
            ["Steel (Structural Section)", 1.550, "Metal", "kg", 7850],
            ["Steel (Galvanized Sheet)", 2.450, "Metal", "kg", 7850],
            ["Aluminum (Extruded)", 6.670, "Metal", "kg", 2700],
            ["Aluminum (Recycled)", 0.500, "Metal", "kg", 2700],

            // Masonry
            ["Brick (Clay)", 0.240, "Masonry", "kg", 1700],
            ["Brick (Concrete)", 0.120, "Masonry", "kg", 2000],
            ["Block (Aerated Concrete)", 0.300, "Masonry", "kg", 600],

            // Insulation
            ["Glass Wool Insulation", 1.300, "Insulation", "kg", 20],
            ["Stone Wool Insulation", 1.400, "Insulation", "kg", 40],
            ["PIR Foam Board", 4.500, "Insulation", "kg", 30],
            ["EPS (Expanded Polystyrene)", 3.300, "Insulation", "kg", 25],

            // Glass
            ["Glass (Float/Flat)", 0.900, "Glass", "kg", 2500],
            ["Glass (Toughened)", 1.100, "Glass", "kg", 2500],

            // Finishes
            ["Plasterboard", 0.380, "Finishes", "kg", 800],
            ["Plaster (Gypsum)", 0.120, "Finishes", "kg", 1200],
            ["Ceramic Tiles", 0.700, "Finishes", "kg", 2000],
            ["Vinyl Flooring", 2.200, "Finishes", "kg", 1300],
            ["Carpet (Nylon)", 2.800, "Finishes", "kg", 1500]
        ];

        foreach ($materials as $m) {
            $name = $m[0];
            $factor = $m[1];
            $cat = $m[2];
            $unit = $m[3];
            $density = $m[4];

            // Escaping single quotes if necessary
            $nameEsc = str_replace("'", "''", $name);

            $this->addSql(
                "INSERT INTO material (name, carbon_footprint_per_unit, category, unit, density, industry_average_factor) 
                 VALUES ('$nameEsc', $factor, '$cat', '$unit', $density, NULL)"
            );
        }

        // Remove created_at from insert if it's not in the previous migration? 
        // Wait, Version...01 didn't have created_at? 
        // Checking Version...00 (Postgres manual one): "CREATE TABLE material (id INT ... name ... category ...)" - NO created_at.
        // Version...01 (Repair) dropped and recreated.
        // Checking my memory of Version...01:
        // $this->addSql('CREATE TABLE material (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, carbon_footprint_per_unit DOUBLE PRECISION NOT NULL, category VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        // It DOES NOT have created_at. 
        // I must be careful. I will NOT insert created_at.
    }

    // REDOING THE UP METHOD IN MY HEAD:
    // The previous migration Version20251231000001.php did NOT create 'created_at'.
    // So I should NOT try to insert it.
}
